services:
  backend:
    build:
      context: ./server
    container_name: backend-fastify
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./infrastructure/logging/logs/app.log:/app/app.log
      - ./server/code/backend-fastify/database.sqlite:/app/database.sqlite
    networks:
      - elk-net

  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enrollment.enabled=${ELASTIC_SSL_ENABLED}
      - xpack.security.http.ssl.enabled=${ELASTIC_SSL_ENABLED}
      - xpack.security.http.ssl.keystore.path=/usr/share/elasticsearch/config/certs/elasticsearch.p12
      # - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/elasticsearch.key
      # - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/elasticsearch.crt
    ports:
      - 9200:9200
    networks:
      - elk-net
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esconfig:/usr/share/elasticsearch/config
      - ${ELASTIC_CERTS_PATH}:/usr/share/elasticsearch/config/certs

  kibana:
    image: kibana:8.12.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elk-net
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${KIBANA_USER}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASS}
      - SERVER_SSL_ENABLED=${ELASTIC_SSL_ENABLED}
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/kibana.crt
      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/kibana.key
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    volumes:
      - kibdata:/usr/share/kibana/data
      - ./${ELASTIC_CERTS_PATH}:/usr/share/kibana/config/certs

  logstash:
    image: logstash:8.12.0
    container_name: logstash
    volumes:
      - ./infrastructure/logging/logs/app.log:/usr/share/logstash/logs/app.log
      - ./infrastructure/logging/logs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        - ./${ELASTIC_CERTS_PATH}:/usr/share/logstash/config/certs
    networks:
      - elk-net
    depends_on:
      - elasticsearch
    environment:
      - ELASTIC_CERTS_PATH=${ELASTIC_CERTS_PATH}

  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./infrastructure/performance/k6-script.js:/k6-script.js
      - ./infrastructure/performance/k6-script-db-test.js:/k6-script-db-test.js  
    networks:
      - elk-net
    entrypoint: ["sleep", "infinity"]
    depends_on:
      - backend

networks:
  elk-net:
    driver: bridge

volumes:
  esdata:
  kibdata:
  esconfig: