services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api-gateway
    networks:
      - "transcendence"
  api-gateway:
    build: ./api-gateway
    image: api-gateway:1.0.0
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
    networks:
      - "transcendence"
      - "game"
    volumes:
      - api-gateway:/app/public
      - ./shared/ip/server.ip:/app/shared/server.ip:ro
      - flappy-bird-dist:/app/public/flappy-bird
      - pong-dist:/app/public/pong
  auth-service:
    build: ./auth-service
    image: auth-service:1.0.0
    container_name: auth-service
    depends_on:
      - sqlite-db
    networks:
      - "transcendence"
      - "db_connection"
  users-service:
    build: ./users-service
    image: users-service:1.0.0
    container_name: users-service
    depends_on:
      - sqlite-db
    networks:
      - "transcendence"
      - "db_connection"
    volumes:
      - users-service:/app/assets
  sqlite-db:
    build: ./sqlite-db
    image: sqlite-db:1.0.0
    container_name: sqlite-db
    restart: always
    networks:
      - "db_connection"
    volumes:
      - sqlite-db:/app/database
      - ./shared/ssl:/app/ssl:ro
  chat-service:
    build: ./chat-service
    image: chat-service:1.0.0
    container_name: chat-service
    networks:
      - "transcendence"
      - "db_connection"
  game-server:
    build: ./game-server
    image: game-server:1.0.0
    container_name: game-server
    networks:
      - "game"
      - "transcendence"
    volumes:
      - ./shared/game-stats.json:/app/game-stats.json
  game-pong:
    build: ./game-pong
    image: game-pong:1.0.0
    container_name: game-pong
    depends_on:
      - game-server
    networks:
      - "game"
    volumes:
      - ./shared/ip/server.ip:/app/public/server.ip:ro
      - ./shared/game-stats.json:/app/public/game-stats.json:ro
      - pong-dist:/usr/share/nginx/html
  match-service:
    build: ./match-service
    image: match-service:1.0.0
    container_name: match-service
    depends_on:
      - game-server
    networks:
      - "game"
      - "transcendence"
    env_file:
      - ./match-service/.env
    volumes:
      - ./shared/ip/server.ip:/app/shared/server.ip:ro
  game-flappy-bird:
    build: ./game-flappy-bird
    image: game-flappy-bird:1.0.0
    container_name: game-flappy-bird
    networks:
      - "game"
    volumes:
      - flappy-bird-dist:/usr/share/nginx/html
volumes:
  sqlite-db:
  users-service:
  api-gateway:
  flappy-bird-dist:
  pong-dist:
networks:
  game:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
          gateway: 172.29.0.1

  transcendence:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

  db_connection:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

