services:
  api-gateway:
    build: ./api-gateway
    image: api-gateway:1.0.0
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
    networks:
      - "transcendence"
  auth-service:
    build: ./auth-service
    image: auth-service:1.0.0
    container_name: auth-service
    depends_on:
      - sqlite-db
    networks:
      - "transcendence"
      - "db_connection"
  users-service:
    build: ./users-service
    image: users-service:1.0.0
    container_name: users-service
    depends_on:
      - sqlite-db
    networks:
      - "transcendence"
      - "db_connection"
    volumes:
      - users-service:/app
  sqlite-db:
    build: ./sqlite-db
    image: sqlite-db:1.0.0
    container_name: sqlite-db
    restart: always
    networks:
      - "db_connection"
    volumes:
      - sqlite-db:/app/database
  game-server:
    build: ./game-server
    image: game-server:1.0.0
    container_name: game-server
    ports:
      - 8443:8443
    networks:
      - "transcendence"
volumes:
  sqlite-db:
  users-service:
networks:
  transcendence:
    driver: bridge
  db_connection:
    driver: bridge
