global:
  resolve_timeout: 5m
  smtp_smarthost: 'mailpit:1025'
  smtp_from: 'alertmanager@transcendence.local'
  smtp_require_tls: false

route:
  receiver: devnull
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  routes:
    - receiver: email
      continue: true
    - receiver: webhook
      continue: true

receivers:
  - name: webhook
    webhook_configs:
      - url: http://alert-receiver:8080/alerts
        send_resolved: true
  - name: email
    email_configs:
      - to: dev@transcendence.local
        send_resolved: true
  - name: devnull
